In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

### Read this First

#### Remember that `tab` is is useful for autocompletion.

#### Remember that `shift + tab` is useful for rapidly obtaining usage + documentation.


### Basic Shapes and Types in NumPy

**Create a 1-D array of 5 zeros named `array_of_zeros`. Print it, verify that its shape is `[5]`, and print its `dtype`.**

In [2]:
array_of_zeros = np.zeros(5)
print(array_of_zeros)
print("Array shape: ", array_of_zeros.shape)
print("Array data type: ", array_of_zeros.dtype)

[0. 0. 0. 0. 0.]
Array shape:  (5,)
Array data type:  float64


**Print the transpose of `array_of_zeros`.**

In [3]:
print(array_of_zeros.T)

[0. 0. 0. 0. 0.]


**In the following Markdown Cell, answer:**

**Is its transpose what you expected? Why or why not?**

The transpose is what I expected. In math, the transpose is supposed to be a vector/ matrix/ tensor that has its rows and columns flipped. However, in numpy, normal 1D arrays are represented by a series of entries without rows or columns, so the transpose cannot flip them. If we wanted the regular math definition of the transpose, we could add a new axis.

**Create a 2-D array of 5 zeros, named `array_of_zeros`, with shape `[1, 5]`. Print it, and print its shape.**

In [4]:
array_of_zeros = array_of_zeros[np.newaxis,:]
print(array_of_zeros)
print("Array shape: ", array_of_zeros.shape)

[[0. 0. 0. 0. 0.]]
Array shape:  (1, 5)


**Print the transpose of `array_of_zeros`.**

In [5]:
print(array_of_zeros.T)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


**In the following Markdown Cell, answer:**

**Is its transpose what you expected? Why or why not?**

This is what I expected, since another dimension was added, we can now take the transpose (flip the rows and columns).

**Create a 1-D array of 5 zeros, named `array_of_zeros`, with a `dtype` of `np.float`. Print it, and its `dtype`.**

In [6]:
array_of_zeros = np.zeros(5, dtype=np.float)
print(array_of_zeros)
print("Array data type: ", array_of_zeros.dtype)

[0. 0. 0. 0. 0.]
Array data type:  float64


**In the following Markdown Cell, answer:**

**Does this array contain floats with 32 bit precision or 64 bit precision?**

It contains 64 bit precision.

**Create a 1-D array of 5 zeros, named `array_of_zeros`, with a `dtype` of `np.int`. Print it, and its `dtype`.**

In [7]:
array_of_zeros = np.zeros(5, dtype=np.int)
print(array_of_zeros)
print("Array data type: ", array_of_zeros.dtype)

[0 0 0 0 0]
Array data type:  int64


**In the following Markdown Cell, answer:**

**Does this array contain 32-bit integers or 64-bit integers?**

It contains 64 bit integers.

When dealing with GPUs, we will often want to use 32 bit precision.

**Create a 1-D array of 5 zeros, named `array_of_zeros`, with a `dtype` of `np.float32`. Print it, and its `dtype`.**

In [8]:
array_of_zeros = np.zeros(5, dtype=np.float32)
print(array_of_zeros)
print("Array data type: ", array_of_zeros.dtype)

[0. 0. 0. 0. 0.]
Array data type:  float32


**Create a 1-D array of 5 zeros, named `array_of_zeros`, with a `dtype` of `np.float`, and then create `array_of_zeros_32` by casting `array_of_zeros`. Print it, and its `dtype`.**

In [9]:
array_of_zeros = np.zeros(5, dtype=np.float)
array_of_zeros_32 = array_of_zeros.astype(np.float32)

print(array_of_zeros_32)
print("Array data type: ", array_of_zeros_32.dtype)

[0. 0. 0. 0. 0.]
Array data type:  float32


### `np.arange`, Element-Wise Operations, and Reshaping

**Create `x1` to be a 1-D array of floats containing `[0, 1, 2, 3, 4]`, but do not type these values explicitly; instead, use `np.arange`. Also create `x2` in the exact same way. Print `x1`, `x2`, and `x1`'s `dtype`. Be sure `x1` and `x2` store floats, not ints.**

In [10]:
x1 = np.arange(5, dtype=np.float32)
x2 = np.arange(5, dtype=np.float32)

print("x1: ", x1)
print("x2: ", x2)

print("x1 data type: ", x1.dtype)
print("x2 data type: ", x2.dtype)

x1:  [0. 1. 2. 3. 4.]
x2:  [0. 1. 2. 3. 4.]
x1 data type:  float32
x2 data type:  float32


**Create `y` via `y = x1 + x2`. Print `y` and its `dtype`.**

In [11]:
y = x1 + x2
print("y: ", y)
print("y data type: ", y.dtype)

y:  [0. 2. 4. 6. 8.]
y data type:  float32


**Reshape `x1` to have shape `[1, 5]` and `x2` to have shape `[5, 1]`. Print their shapes.**

In [12]:
x1.reshape(1,5)
x2.reshape(5,1)

print("x1 shape: ", x1.shape)
print("x2 shape: ", x2.shape)

x1 shape:  (5,)
x2 shape:  (5,)


**Form `y` via `y = x1 + x2`. Print `y`.**

In [13]:
y = x1 + x2
print(y)

[0. 2. 4. 6. 8.]


**In the following Markdown Cell, answer:**

**Is this what you expected? (For now, just a 'Yes' or 'No' is fine; we will revisit this result later.)**

Yes, the x1 and x2 vectors were broadcast over their dimension of size 5, resulting in a 5 by 5 array.

**Create a 1-D array x containing integers 0, 1, ..., 8 using `np.arange`. Print it, and its `dtype`.**

In [14]:
x = np.arange(9, dtype=np.float32)
print("x: ", x)
print("x data type: ", x.dtype)

x:  [0. 1. 2. 3. 4. 5. 6. 7. 8.]
x data type:  float32


**Create `X` by reshaping `x` to have shape `[3, 3]`. Print `X`.**

In [15]:
X = x.reshape(3,3)
print(X)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


NumPy arrays are typically contiguous strips of memory, with the shape specifying how we view that memory. For example, if the shape of the strip of memory `[0, 1, 2, 3]` is `[2, 2]`, then we view it as a 2 x 2 matrix.


**In the following Markdown Cell, answer:**


**Given your previous `reshape` result, and the fact that `reshape` only changes our view of a contiguous strip of memory, do *rows* have elements that are mutually closer in memory, or do *columns* have elements that are mutually closer in memory?**

Rows have elements that are closer in memory.

### Element-Wise Multiplication vs. Matrix Multiplication

**Create `A` and `B`, each 2-D matrices of ones with shape `[3, 3]`.**

In [16]:
A = np.ones((3,3))
B = np.ones((3,3))

**Form `C_star` via `C_star = A * B`, and print `C_star`.**

In [17]:
C_star = A * B
print(C_star)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Form `C_at` via `C_at = A @ B`, and print `C_at`.**

In [18]:
C_at = A @ B
print(C_at)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


**In the following Markdown Cell, answer:**

**What operation does `*` perform? What operation does `@` perform?**

The * opereraor performs a hadamard matrix multiplication (element wise). The @ operator performs a regular matrix multiplication.

### Broadcasting

Suppose you have some data collected in a 1-D array, which is not 'normalized' in the sense that it has a mean that's far from 0 and a standard deviation that's far from 1:

In [19]:
x = np.array([3.2, 1.1, 1.2, 5.3, 3.9, 1.9, 2.0, 6.2, 1.0, 2.2])
print(x.mean())
print(x.std())

2.8
1.7227884373886422


**Form `z` by normalizing `x`. That is, each entry in `z` should be the *standardized score* of the corresponding entry in `x`: $z_i = (x_i - \mu) / \sigma$. Print `z` and verify that its mean is close to 0.0 and that its standard deviation is close to 1.0.**

In [20]:
z = (x - x.mean()) / x.std()
print(z)
print(z.mean())
print(z.std())

[ 0.23218173 -0.98677235 -0.92872692  1.45113581  0.63849976 -0.52240889
 -0.46436346  1.97354471 -1.04481779 -0.3482726 ]
9.992007221626409e-17
1.0000000000000002


Now suppose that you have 5 3-dimensional feature vectors collected in an array, and that none of the features are normalized, in that each feature has a mean that's far from 0 and a standard deviation that's far from 1:

In [21]:
data = np.array([[7.5, -1.1,  1.6],
                 [0.1,  0.9, -0.7],
                 [6.3, -0.9,  3.1],
                 [2.5, -0.6,  0.4],
                 [2.4, -0.1,  1.0]])
print(data.mean(axis=0))
print(data.std(axis=0))

[ 3.76 -0.36  1.08]
[2.73027471 0.71442284 1.26396202]


**Write code to normalize this data on a feature-wise basis, so that each feature has mean 0 and standard deviation 1, and store the result in `normalized_data`. Print `normalized_data` along with its per-feature mean and its per-feature standard deviation.**

In [22]:
normalized_data = (data - data.mean(axis=0)) / data.std(axis=0)
print(normalized_data)
print(normalized_data.mean(axis=0))
print(normalized_data.std(axis=0))

[[ 1.36982553 -1.03580115  0.41140477]
 [-1.34052445  1.76366141 -1.40827016]
 [ 0.93030932 -0.75585489  1.59814928]
 [-0.46149202 -0.33593551 -0.53799085]
 [-0.49811837  0.36393013 -0.06329304]]
[ 1.88737914e-16  1.11022302e-17 -5.55111512e-18]
[1. 1. 1.]


Now suppose that you have 3 3-D vectors that each represent *unnormalized class scores*. That is, each 3-D vector represents the scores for three different classes in a classification problem. (For example, these could be the outputs of an image-classification model, with each row corresponding to a particular image and each column corresponding to a particular class, such as 'dog', 'cat', or 'other'.)

If each row represented a valid probability distribution, then their elements would sum do 1, but they currently do not:

In [23]:
scores = np.array([[8.2, 6.7, 6.3],
                   [9.5, 0.2, 9.3],
                   [3.6, 2.7, 9.0]])
print(scores)
print(scores.sum(axis=1))

[[8.2 6.7 6.3]
 [9.5 0.2 9.3]
 [3.6 2.7 9. ]]
[21.2 19.  15.3]


**Write code to compute and print the array `probabilities` by dividing each row of `scores` by its sum. Print `probabilities` and the sum of each of its rows, to verify that each row sums to 1.** Hint: If the rows do not sum to 1, then think about broadcasting and take a look at the `keepdims` keyword argument of NumPy's `sum` function.

In [24]:
probabilities = scores / scores.sum(axis=1, keepdims=True)
print(probabilities)
print(probabilities.sum(axis=1))

[[0.38679245 0.31603774 0.29716981]
 [0.5        0.01052632 0.48947368]
 [0.23529412 0.17647059 0.58823529]]
[1. 1. 1.]


**Complete the `tril_` function below by inserting only 2 lines of code at the bottom of the function.** Hint: Form a mask using broadcasting, and use the mask to modify `X` in place.

In [25]:
def tril_(X):
    """Modify X in place to become lower triangular.

    Args:
        X: A 2-D NumPy array with shape [M, N].
    """
    if X.ndim != 2:
        raise ValueError('X must be a 2-D array.')
    M, N = X.shape
    i = np.arange(M).reshape(1, M)
    j = np.arange(N).reshape(N, 1)
    
    mask = (i - j) <= 0
    X *= mask
    pass

**Create a random matrix `X` with shape `[3, 3]` using `np.random.rand`, run `tril_(X)`, and verify that `X` is now lower triangular.**

In [26]:
X = np.random.rand(3,3)
tril_(X)
print(X)

[[0.45696298 0.         0.        ]
 [0.04101766 0.42226696 0.        ]
 [0.54113984 0.3474606  0.1967933 ]]


**Create a random matrix `X` with shape `[5, 5]` using `np.random.rand`, run `tril_(X)`, and verify that `X` is now lower triangular.**

In [27]:
X = np.random.rand(5,5)
tril_(X)
print(X)

[[0.20758945 0.         0.         0.         0.        ]
 [0.33044988 0.21386879 0.         0.         0.        ]
 [0.84584293 0.97574761 0.1837604  0.         0.        ]
 [0.95087855 0.05716833 0.86785703 0.5836643  0.        ]
 [0.31453914 0.09452626 0.62963271 0.86748326 0.85145762]]


### Booleans vs. Masks

**Create `x` using `x = np.array([1, 2, 3])`, and create `y` using `y = x`.**

In [28]:
x = np.array([1, 2, 3])
y = x

**Print the expression `x == y`.**

In [29]:
print(x == y)

[ True  True  True]


**Use `np.all` to test whether *all* elements of `x` are equal to their corresponding elements in `y`. You should print the result, which should be a single boolean, `True` or `False`.**

In [30]:
print(np.all(x == y))

True


**Modify the 0-th element of `y` via `y[0] = 5`, and again use `np.all` to test whether all elements of `x` are equal to their corresponding elements in `y`, and again print the result.**

In [31]:
y[0] = 5
print(np.all(x == y))

True


**In the Markdown Cell below, answer:**

**Is the last result what you expected? Explain what is happening here.**

This makes sense because we did a shallow copy of x to create y. Hence x and y refer to the same memory and so when we modified y we also modified x.

**Create `x = np.array([1, 2, 3])` and `y = np.array([2, 2, 2])`. Again use `np.all` to test whether all elements of `x` are equal to their corresponding elements in `y`, and again print the result.**

In [32]:
x = np.array([1, 2, 3])
y = np.array([2, 2, 2])
print(np.all(x == y))

False


**Use `np.any` to test whether *any* elements of `x` are equal to their corresponding elements in `y`, and again print the result.**

In [34]:
print(np.any(x == y))

True
